apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:dgadavin/argocd-example-apps.git
    targetRevision: 
    path: helm-dependency
  destination:
    server: https://kubernetes.default.svc
    namespace: 
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
