apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-100
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:dgadavin/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-dependency
  destination:
    server: https://kubernetes.default.svc
    namespace: test-100
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
