name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Generate new app
      run: |
        DEPLOY_BRANCH=$(echo $GITHUB_REF | cut -d / -f 4)
        echo "DEPLOY_BRANCH=$(echo $GITHUB_REF | cut -d / -f 4)" >> $GITHUB_ENV
        sed  "s/%%BRANCH%%/${DEPLOY_BRANCH}/g" job.template > seed-jobs/dev/${DEPLOY_BRANCH}.yaml
    - name: Checkout to seed-job branch
      uses: actions/checkout@v2
      with:
        ref: seed-job
    - name: Commit files
      run: |
        git config --local user.email "test@example.com"
        git config --local user.name "github-actions[bot]"
        git add seed-jobs/dev/${DEPLOY_BRANCH}.yaml
        git commit -m "[skip ci] Add new ${DEPLOY_BRANCH} application" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: seed-job
